services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    env_file:
      - .env
    ports:
      - "9999:8000"
    depends_on:
#      - db
      - redis
    restart: on-failure
    command: > 
      sh -c "python manage.py wait_db && python manage.py migrate && python manage.py loaddata catalog_fixture.json && python manage.py seed_forbidden_words && python manage.py fetch_exchange_rates && python manage.py runserver 0.0.0.0:8000"
#  db:
#    image: mysql:8
#    env_file:
#      - .env
#    ports:
#      - "3310:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    env_file:
      - .env
    depends_on:
      - redis
#      - db
    restart: on-failure
    command: sh -c "celery -A configs worker -l info"
  celery-beat:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
#      - db
    restart: on-failure
    command: sh -c "celery -A configs beat -l info"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/usr/share/nginx/html/static
      - ./backend/storage:/usr/share/nginx/html/storage 
    depends_on:
      - app