# Generated by Django 6.0.6 on 2026-06-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradmodel',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.bodytypemodel'),
        ),
        migrations.AddField(
            model_name='caradmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.brandmodel'),
        ),
        migrations.AddField(
            model_name='caradmodel',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.carmodelmodel'),
        ),
        migrations.AddField(
            model_name='caradmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.citymodel'),
        ),
    ]
