# Generated by Django 6.0.6 on 2026-06-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_initial'),
        ('catalog', '0001_initial'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradmodel',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='dealerships.dealershipmodel'),
        ),
        migrations.AddField(
            model_name='caradmodel',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.fueltypemodel'),
        ),
    ]
