# Generated by Django 6.0.6 on 2026-06-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0003_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caradmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caradmodel',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.transmissionmodel'),
        ),
        migrations.AddField(
            model_name='adviewmodel',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ads.caradmodel'),
        ),
        migrations.AddField(
            model_name='carimagemodel',
            name='car_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.caradmodel'),
        ),
    ]
