# Generated by Django 6.0.6 on 2026-06-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealerships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipemployeemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealershipemployeemodel',
            name='dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dealerships.dealershipmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='dealershipemployeemodel',
            unique_together={('user', 'dealership')},
        ),
    ]
